version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the application..."
  post_build:
    commands:
      - echo "Build completed successfully."
      - echo "Starting tests..."
      - npm test
      - echo "Tests completed successfully."
      - echo "Cleaning up..."
      - npm run clean || echo "No clean script"

artifacts:
  files:
    - build/**/*     # or dist/**/* depending on your Node.js build output
  name: builds/$CODEBUILD_BUILD_NUMBER/my-artifacts
